name: CI
on: push

jobs:
  deploy-yarn:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish --tag beta
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
