name: CI
on: push

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: git config --global user.name 'Sohail Haider'
      - run: git config --global user.email 'sohailhaider@icloud.com'
      - run: npm version prerelease --preid beta
      - run: git push
