name: CI
on: 
  push:
    branches:    
      - 'master'
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:    
      - 'master'

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[BETA RELEASE]')"
    steps:
      - uses: actions/checkout@v2
      - run: |
          set +x
          echo $GITHUB_ACTOR
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          npm version prerelease --preid beta -m "[BETA RELEASE] %s"
          git push

