name: CI
on: 
  push:
    branches:    
      - 'master'
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:    
      - 'master'

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[BETA RELEASE]')"
    steps:
      - uses: actions/checkout@v2
      - run: |
          set +x
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          npm version prerelease --preid beta -m "[BETA RELEASE] %s"
          git push && git push --tags
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npm publish --tag beta
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

