name: CI
on: 
  push:
    branches:    
      - 'master'

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[BETA RELEASE]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: |
          set +x
          git config --global user.name 'Sohail Haider'
          git config --global user.email 'sohail.haider@autoscout24.com'
          npm version prerelease --preid beta -m "[BETA RELEASE] %s"
          git push && git push --tags
